baseURL = "https://mj-seok.com/"
languageCode = "en-us"
title = "Happiness Development"
googleAnalytics = "UA-154649876-1"
theme = "github-style"

[params]
  author = "Jose Seok"
  description = "Happiness Development"
  github = "MinlleSeok"
  email = "my@mj-seok.com"
  utterances = "MinlleSeok/minlleseok.github.io"
  avatar = "https://mj-seok.com/images/avatar.png"
  url = "https://mj-seok.com"