baseURL = "https://minlleseok.github.io/"
languageCode = "en-us"
title = "Happiness Development"
googleAnalytics = "UA-154649876-1"
theme = "github-style"

[params]
  author = "Jose Seok"
  description = "Happiness Development"
  github = "MinlleSeok"
  email = "hotheating@gmail.com"
  utterances = "MinlleSeok/minlleseok.github.io"
  avatar = "https://minlleseok.github.io/images/avatar.jpg"
  url = "https://minlleseok.github.io"